version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: recyclewebsite
      POSTGRES_USER: recycleuser
      POSTGRES_PASSWORD: recyclepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data:
